import { TrendingUp } from "lucide-react";

const regions = [
  { name: "East", revenue: "$1.1M", height: "60%", delay: "0s" },
  { name: "North", revenue: "$1.4M", height: "80%", delay: "0.1s" },
  { name: "West", revenue: "$0.8M", height: "45%", delay: "0.2s" },
  { name: "South", revenue: "$1.2M", height: "65%", delay: "0.3s" },
];

export const RevenueChart = () => {
  return (
    <div className="p-6 bg-card rounded-2xl shadow-xl ring-1 ring-border backdrop-blur-sm">
      <div className="flex justify-between items-center mb-6">
        <h4 className="text-lg font-semibold text-foreground">Quarterly Revenue (Q3)</h4>
        <span className="flex items-center gap-1.5 text-xs font-medium text-success bg-success/10 px-3 py-1.5 rounded-full ring-1 ring-success/20">
          <TrendingUp className="h-3 w-3" />
          +15% vs Q2
        </span>
      </div>
      
      <div className="w-full h-64 flex items-end justify-around gap-4 p-4 border-b-2 border-l-2 border-border rounded-bl-lg">
        {regions.map((region, index) => (
          <div
            key={index}
            className="flex flex-col items-center space-y-2 flex-1"
          >
            <div className="text-sm font-semibold text-foreground">
              {region.revenue}
            </div>
            <div
              className="chart-bar w-full bg-gradient-to-t from-primary to-accent rounded-t-lg shadow-lg"
              style={{
                height: region.height,
                animationDelay: region.delay,
              }}
            />
            <div className="text-xs text-muted-foreground font-medium pt-1">
              {region.name}
            </div>
          </div>
        ))}
      </div>
      
      <p className="text-xs text-muted-foreground mt-4 text-center">
        Data automatically generated by Gemini from your query.
      </p>
    </div>
  );
};
